
title: DMPR
#url: "https://long-pig.cloudvent.net"
baseurl:
google_analytics_key:
show_full_navigation: true

logo: /siteicon.png
description: Product documentation template for Jekyll.
author:
  name: Hagen Paul Pfeifer
  email: hagen@jauu.net
  twitter: hgnize
social:
  name: Dynamic MultiPath Routing Protocol
  links:
    - https://github.com/CloudCannon/edition-jekyll-template


permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
