runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*)/
  static_files: \1/index.html
  upload: (.*)/index.html

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?\..*
- \.gitignore
- ^\.git/.*
